### ISSUE TITLE
udb_hash. 

### ISSUE THREAD

**Issue by DobbysGamertag** [PutuSuhartawan/Scripting-Pawn-SAMP-Belajar-Dasar#2]
The `udb_hash` function is not good for hashing user passwords. You should consider switching to bcrypt so user passwords are more secure. 

Bcrypt is available here: https://github.com/Sreyas-Sreelal/samp-bcrypt

https://github.com/PutuSuhartawan/Scripting-Pawn-SAMP-Belajar-Dasar/blob/1e2ccea189c2d34218f41ce34ed9c17ef52879b0/storage/GM%20with%20INI%20database.pwn#L83

**Comment by PutuSuhartawan** [comment]
What function is better sir?
`bcrypt_get_hash(dest); `?

**Comment by DobbysGamertag** [comment]
Hi :) 

You can find an example lower down on the readme. Here: https://github.com/lassir/bcrypt-samp#example

**Comment by PutuSuhartawan** [comment]
Recommend issue:
https://github.com/Sreyas-Sreelal/samp-bcrypt/blob/f52365d782b0e08f11f7e3e052694b4ece9778e3/pawn-tests/test.pwn#L14
